- name: add vpn users (ignore errors)
  become: true
  become_user: root
  command: "{{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /HUB:default /CMD {{ item }}"
  loop:
    - UserCreate {{ vpn_user }} /GROUP:none /REALNAME:none /NOTE:none
    - UserPasswordSet {{ vpn_user }} /PASSWORD:{{ vpn_pass }}
  ignore_errors: true



- name: enable L2TP over IPsec
  become: true
  become_user: root
  command: >
    {{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /ADMINHUB:default /CMD
    IPsecEnable /L2TP:yes /L2TPRAW:no /ETHERIP:no /PSK:{{ vpn_shared_pass }} /DEFAULTHUB:default
  run_once: true

- name: additional settings
  become: true
  become_user: root
  command: "{{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /HUB:default /CMD {{ item }}"
  loop:
    - SecureNatEnable
    - NatEnable
    - DHCPEnable
    - DhcpSet /START:{{ start_ip }} /END:{{ end_ip }} /MASK:{{ netmask }} /EXPIRE:{{ lease }}  /GW:{{ gateway }} /DNS:{{ dns }} /DNS2:{{ dns2 }} /DOMAIN:{{ domain }} /LOG:{{ log }} /PUSHROUTE:{{ route_to_hcintnetwork }}