softether_dir: /opt/softether
vpnserver_src: https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.38-9760-rtm/softether-vpnserver-v4.38-9760-rtm-2021.08.17-linux-x64-64bit.tar.gz

vpn_user: test_user
vpn_pass: test_password
vpn_shared_pass: test1234
